name: recipe_app
description: Recipe App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  retrofit: ^4.0.1
  json_annotation: ^4.8.0
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.14
  path: ^1.8.2
  flutter_bloc: ^8.1.2
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.4
  cached_network_image: ^3.2.3
  settings_ui: ^2.0.2
  get_it: ^7.2.0
  injectable: ^2.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  flutter_markdown: ^0.6.14
  html2md: ^1.2.6
  drift_db_viewer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  drift_dev: ^2.6.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 16

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets\font\sf_pro_regular.ttf
        - asset: assets\font\sf_pro_medium.ttf
          weight: 500
        - asset: assets\font\sf_pro_semibold.ttf
          weight: 600